fix android app
artux-net/ailingo-app pull request #13
Opened 2024-11-10 18:14 UTC by VangelNum

Адаптировал экраны для android

2024-11-15 18:46 UTC, prygunov requested changes

2024-11-15 18:55 UTC, VangelNum commented on composeApp/src/commonMain/kotlin/org/ailingo/app/core/navigation/presentation/NavigationForDesktop.kt
> +                if (showTopAppBarWithProfile == true) {
ахахаххах

2024-11-15 18:57 UTC, VangelNum commented on composeApp/src/androidMain/kotlin/org/ailingo/app/Utils.kt
> +    println(configuration)
полезный принтлн, ты не шаришь.

2024-11-15 19:55 UTC, prygunov commented on composeApp/src/androidMain/kotlin/org/ailingo/app/Utils.kt
> +    println(configuration)
логгер есть

2024-11-15 21:14 UTC, VangelNum commented on composeApp/src/androidMain/kotlin/org/ailingo/app/Utils.kt
> +    println(configuration)
со своими задачами справляется, считаются логгер избыточен

2024-11-16 20:01 UTC, prygunov requested changes

2024-11-16 20:01 UTC, prygunov commented on composeApp/src/commonMain/kotlin/org/ailingo/app/core/navigation/presentation/NavigationForDesktop.kt
> +                if (showTopAppBarWithProfile == true) {
кажется ты не исправил, 1 в 1 как в меме 

![Uploading image.png…]()

2024-11-16 20:01 UTC, prygunov commented on composeApp/src/commonMain/kotlin/org/ailingo/app/core/navigation/presentation/NavigationForDesktop.kt
> +                if (showTopAppBarWithProfile == true) {
еще тут у boolean три состояния блин, почему не сделать два как у нормального человека?

2024-11-16 21:06 UTC, VangelNum commented on composeApp/src/commonMain/kotlin/org/ailingo/app/features/topics/presentation/ContentTopics.kt
> +                style = if (type == "desktop") MaterialTheme.typography.headlineMedium else MaterialTheme.typography.titleLarge,
enum class DeviceType {
    Desktop, Mobile
}

2024-11-16 21:12 UTC, prygunov approved these changes

2024-11-16 21:36 UTC, merged